### ISSUE TITLE
Missing parameter in snippets_dock.gd

### ISSUE THREAD

**Issue by TheSylkie** [gswashburn/Snippets-EditorPlugin#1]
Windows 10, Godot 3.1.2

After activating the plugin I received these errors.

> 
 res://addons/snippets_plugin/snippets_dock.gd:20 - Parse Error: Too few arguments for 'check_dir()' call. Expected at least 1.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://addons/snippets_plugin/plugin.gd:20 - Invalid set index 'ext_editor_path' (on base: 'Panel (snippets_dock.gd)') with value of type 'String'.

In line 20 of snippets_dock.gd, the second check is to see if the directory exists, but no parameter is passed to the check_dir function. I fixed it by adding snippets_path as a parameter to check_dir.

`#Original
#if not config.has_section_key("location", "snippets_folder") or check_dir() == false: # Or Folder not found ~ var added to dir check RER 2/23/02

#Changed to
	if not config.has_section_key("location", "snippets_folder") or check_dir(snippets_path) == false: # Or Folder not found` 

So far, so good!

The snippets directory that is referenced in snippets_config does not exist on my machine, after pointing to a good directory, everything works fine.

**Comment by gswashburn** [comment]
Thanks, for the fix. This was incorporated in a current merge from avril-gh. I appreciate that this project is getting some traction, It would be great if we could get it added to the Godot Editor and not be an addon.
